/**
 * Canonical sector/industry taxonomy for diversification analysis.
 * Mirrors backend/app/core/taxonomy.py — keep both in sync manually.
 *
 * Sector and industry values stay in English by explicit exception to the
 * Czech-only UI rule: they're international financial classification terms
 * (same treatment as exchange codes / tickers), and the value must match
 * what's stored in the DB and returned by yfinance.
 */

export const SECTOR_KEYS = [
  'Technology',
  'Financial Services',
  'Utilities',
  'Energy',
  'Real Estate',
  'Healthcare',
  'Consumer Cyclical',
  'Consumer Defensive',
  'Industrials',
  'Basic Materials',
  'Communication Services',
] as const;

export const SECTOR_CHOICES = [...SECTOR_KEYS, 'ETF/Fund', 'Cryptocurrency'] as const;

export type Sector = (typeof SECTOR_CHOICES)[number];

export const SECTOR_OPTIONS = SECTOR_CHOICES.map((value) => ({ value, label: value }));

export const INDUSTRY_TAXONOMY: Record<string, string[]> = {
  Technology: [
    'Information Technology Services',
    'Software - Application',
    'Software - Infrastructure',
    'Communication Equipment',
    'Computer Hardware',
    'Consumer Electronics',
    'Electronic Components',
    'Electronics & Computer Distribution',
    'Scientific & Technical Instruments',
    'Semiconductor Equipment & Materials',
    'Semiconductors',
    'Solar',
    'Technology Distributors',
  ],
  'Financial Services': [
    'Asset Management',
    'Banks - Diversified',
    'Banks - Regional',
    'Capital Markets',
    'Credit Services',
    'Financial Conglomerates',
    'Financial Data & Stock Exchanges',
    'Insurance - Diversified',
    'Insurance - Life',
    'Insurance - Property & Casualty',
    'Insurance - Reinsurance',
    'Insurance - Specialty',
    'Insurance Brokers',
    'Mortgage Finance',
    'Shell Companies',
  ],
  Utilities: [
    'Utilities - Diversified',
    'Utilities - Independent Power Producers',
    'Utilities - Regulated Electric',
    'Utilities - Regulated Gas',
    'Utilities - Regulated Water',
    'Utilities - Renewable',
  ],
  Energy: [
    'Oil & Gas Drilling',
    'Oil & Gas E&P',
    'Oil & Gas Equipment & Services',
    'Oil & Gas Integrated',
    'Oil & Gas Midstream',
    'Oil & Gas Refining & Marketing',
    'Thermal Coal',
    'Uranium',
  ],
  'Real Estate': [
    'Real Estate - Development',
    'Real Estate - Diversified',
    'Real Estate Services',
    'REIT - Diversified',
    'REIT - Healthcare Facilities',
    'REIT - Hotel & Motel',
    'REIT - Industrial',
    'REIT - Mortgage',
    'REIT - Office',
    'REIT - Residential',
    'REIT - Retail',
    'REIT - Specialty',
  ],
  Healthcare: [
    'Biotechnology',
    'Diagnostics & Research',
    'Drug Manufacturers - General',
    'Drug Manufacturers - Specialty & Generic',
    'Health Information Services',
    'Healthcare Plans',
    'Medical Care Facilities',
    'Medical Devices',
    'Medical Distribution',
    'Medical Instruments & Supplies',
    'Pharmaceutical Retailers',
  ],
  'Consumer Cyclical': [
    'Apparel Manufacturing',
    'Apparel Retail',
    'Auto & Truck Dealerships',
    'Auto Manufacturers',
    'Auto Parts',
    'Department Stores',
    'Footwear & Accessories',
    'Furnishings, Fixtures & Appliances',
    'Gambling',
    'Home Improvement Retail',
    'Internet Retail',
    'Leisure',
    'Lodging',
    'Luxury Goods',
    'Packaging & Containers',
    'Personal Services',
    'Recreational Vehicles',
    'Residential Construction',
    'Resorts & Casinos',
    'Restaurants',
    'Specialty Retail',
    'Textile Manufacturing',
    'Travel Services',
  ],
  'Consumer Defensive': [
    'Beverages - Brewers',
    'Beverages - Non-Alcoholic',
    'Beverages - Wineries & Distilleries',
    'Confectioners',
    'Discount Stores',
    'Education & Training Services',
    'Farm Products',
    'Food Distribution',
    'Grocery Stores',
    'Household & Personal Products',
    'Packaged Foods',
    'Tobacco',
  ],
  Industrials: [
    'Aerospace & Defense',
    'Agricultural - Machinery',
    'Airlines',
    'Airports & Air Services',
    'Building Products & Equipment',
    'Business Equipment & Supplies',
    'Conglomerates',
    'Consulting Services',
    'Electrical Equipment & Parts',
    'Engineering & Construction',
    'Farm & Heavy Construction Machinery',
    'Industrial Distribution',
    'Infrastructure Operations',
    'Integrated Freight & Logistics',
    'Marine Shipping',
    'Metal Fabrication',
    'Pollution & Treatment Controls',
    'Railroads',
    'Rental & Leasing Services',
    'Security & Protection Services',
    'Specialty Business Services',
    'Specialty Industrial Machinery',
    'Staffing & Employment Services',
    'Tools & Accessories',
    'Trucking',
    'Waste Management',
  ],
  'Basic Materials': [
    'Agricultural Inputs',
    'Aluminum',
    'Building Materials',
    'Chemicals',
    'Coking Coal',
    'Copper',
    'Gold',
    'Lumber & Wood Production',
    'Other Industrial Metals & Mining',
    'Other Precious Metals & Mining',
    'Paper & Paper Products',
    'Silver',
    'Specialty Chemicals',
    'Steel',
  ],
  'Communication Services': [
    'Advertising Agencies',
    'Broadcasting',
    'Electronic Gaming & Multimedia',
    'Entertainment',
    'Internet Content & Information',
    'Publishing',
    'Telecom Services',
  ],
  'ETF/Fund': ['Equity ETF', 'Bond ETF', 'Commodity ETF', 'Sector ETF', 'REIT ETF'],
  Cryptocurrency: ['Bitcoin', 'Ethereum', 'Stablecoin', 'Altcoin'],
};

export const ALL_INDUSTRIES: readonly string[] = Object.values(INDUSTRY_TAXONOMY).flat();

/** Industry <Select> options for a given sector; empty array if sector unset/unknown. */
export function getIndustryOptions(sector: string | undefined | null) {
  const industries = (sector && INDUSTRY_TAXONOMY[sector]) || [];
  return industries.map((value) => ({ value, label: value }));
}
